# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fad6377f23f44e187821dbc897e6f5ac38b5123c5918cec977272da67b9209931bb97b6f364ad296b26c92f6570bdb1cfc5484d849c814d5044e2b38b70e7e68

test:
  secret_key_base: 9d68d3479f85f545c08bcfc4060f18d4f776c33bc3049f011d182153ae44c92a74652beefb696d3217f51758488b92e2ad1f9439851e60a5d67da55046739da0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
